# Generated by Django 2.2.3 on 2019-07-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('tracking_id', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
                ('embed_url', models.CharField(max_length=500)),
                ('embed_html', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('game', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
