# Generated by Django 2.2.3 on 2019-08-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
